image: node:12.4.0

stages:
  - install
  - build
  # - deploy

# to cache both npm modules we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'

job_install:
  retry: 2
  stage: install
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
  script:
    - npm install

job_build:
  retry: 2
  stage: build
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build

deploy_docs:
  retry: 2
  stage: deploy
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run page
    - rm -rf /var/www/qui-react/master/*
    - cp -R ./docs/* /var/www/qui-react/master
  only:
    - release-1.0.0
